version: 1.0.{build}
image: Visual Studio 2019
install:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
build_script:
- cmd: >-
    git submodule update --init

    msbuild /nologo /m /t:restore /p:Configuration=Release;Platform="Any CPU" RecompressPng.sln

    msbuild /nologo /m /p:Configuration=Release;Platform="Any CPU" RecompressPng.sln

    msbuild /nologo /m /p:Configuration=Release;Platform="x86" RecompressPng.sln

    mkdir Artifacts\RecompressPng\x64

    mkdir Artifacts\RecompressPng\x86

    copy RecompressPng\bin\Release\net5.0\NLog.config Artifacts\RecompressPng\

    copy RecompressPng\bin\Release\net5.0\*.dll Artifacts\RecompressPng\

    copy RecompressPng\bin\Release\net5.0\*.json Artifacts\RecompressPng\

    xcopy /E RecompressPng\bin\Release\net5.0\runtimes Artifacts\RecompressPng\runtimes\

    copy RecompressPng\bin\Release\net5.0\RecompressPng.exe Artifacts\RecompressPng\

    copy RecompressPng\bin\Release\net5.0\x64\*.dll Artifacts\RecompressPng\x64\

    copy RecompressPng\bin\Release\net5.0\x86\*.dll Artifacts\RecompressPng\x86\

    cd Artifacts

    7z a -mx=9 -r ..\RecompressPng.zip RecompressPng

    cd ..
test_script:
- cmd: '"Artifacts\RecompressPng\RecompressPng.exe" -h'
artifacts:
- path: RecompressPng.zip
  name: PNG re-compressing tool with Zopfli Compression Algorithm
