version: 1.0.{build}
image: Visual Studio 2019
init:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
build_script:
- cmd: >-
    git submodule update --init

    msbuild /nologo /m /t:restore /p:Configuration=Release;Platform="Any CPU" RecompressPng.sln

    msbuild /nologo /m /p:Configuration=Release;Platform="Any CPU" RecompressPng.sln

    msbuild /nologo /m /p:Configuration=Release;Platform="x86" RecompressPng.sln

    dotnet publish --nologo -c Release -o Artifacts\RecompressPng || set ERRORLEVEL=0

    xcopy /Y RecompressPng\bin\Release\net5.0\x64\*.dll Artifacts\RecompressPng\x64\

    xcopy /Y RecompressPng\bin\Release\net5.0\x86\*.dll Artifacts\RecompressPng\x86\

    del Artifacts\RecompressPng\*.pdb

    cd Artifacts

    7z a -mx=9 -r ..\RecompressPng.zip RecompressPng

    cd ..
test_script:
- cmd: '"Artifacts\RecompressPng\RecompressPng.exe" -h'
artifacts:
- path: RecompressPng.zip
  name: PNG re-compressing tool with Zopfli Compression Algorithm
